import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {CumulioDashboardComponent} from "@cumul.io/react-cumulio-dashboard";


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <section>
                    <h1>Icons</h1>
                    <CumulioDashboardComponent
                        authKey="<authkey>"
                        authToken="<authToken>"
                        dashboardId="<dashboardId>"
                    />
                </section>
            </main>
        </>
    )
}
